name: Docker Release

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Process version of the tag
      id: version
      uses: ncipollo/semantic-version-action@v1
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Default
      env:
        VERSION: ${{ steps.version.outputs.tag }}
      run: docker buildx build --platform=linux/amd64,linux/arm64/v8 --push --tag chweicki/noria-ui:$VERSION .
